
version: 2

models:
  - name: season_prediction
    description: "2023 NFL season standings projection"
    columns:
      - name: tm
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

