
version: 2

models:
  - name: season_historical_by_year
    description: "2023 NFL season standings projection"
    tests:
      - unique:
          column_name: "(year || '-' || team)"
      - not_null:
          column_name: "(year || '-' || team)"

