---
version: '3'

services:
  dbt:
    image: entechlog/dbt${DBT_VERSION_TAG}
    container_name: dbt
    build: ./docker/dbt/
#    env_file:
#      - ./docker/dbt/.env
    command: 
      - bash 
      - -c 
      - |
        echo "Launching dbt"
        #
        sleep infinity
    restart: unless-stopped
    volumes:
      - type: bind
        source: /C
        target: /C
    ports:
      - "8085:8085"
    environment:
      - TZ=Etc/GMT
